apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "${ service_name }-alb"
  namespace: kong-gateways
  annotations:
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=false
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:123456789012:certificate/32948f18-63d7-4ed9-9882-9448b81351a7"
    alb.ingress.kubernetes.io/healthcheck-path: "/status/ready"
    alb.ingress.kubernetes.io/healthcheck-protocol: "HTTP"
    alb.ingress.kubernetes.io/healthcheck-port: "8100"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/load-balancer-name: "sample-alb-ctl"
    alb.ingress.kubernetes.io/group.name: "sample-alb-ctl"
    alb.ingress.kubernetes.io/subnets: "subnet-abc,subnet-def,subnet-789"
    alb.ingress.kubernetes.io/inbound-cidrs: "0.0.0.0/0"
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "${ service_name }"
            port:
              number: 80
